MovieApp/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
get 'movies', to: 'movies#index'
get 'actors', to: 'actor#index'
get '/movies/:id', to: 'movies#show', as: :movie
get '/actors/:id', to: 'actors#show', as: :actor

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

MovieApp/app/models/actor.rb
class Actor < ApplicationRecord
has_many :parts
has_many :movies, through: :parts

end

MovieApp/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :parts
    has_many :actors, through: :parts
end

MovieApp/app/models/part.rb
class Part < ApplicationRecord
    belongs_to :movie
    belongs_to :actor
end

MovieApp/app/controllers/actors_controller.rb
class ActorsController < ApplicationController

  def index
    @actors = Actor.all
  end

  def show
    @actor = Actor.find(params[:id])
    @movies = @actor.movies
  end
end

MovieApp/app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.all
    end

    def show
        @movie = Movie.find(params[:id])
        @actors = @movie.actors
    end
end

MovieApp/app/helpers/actors_helper.rb
module ActorsHelper
end

MovieApp/app/helpers/movies_helper.rb
module MoviesHelper
end

MovieApp/app/views/actors/index.html.erb
<div class="main actor-index">
      <div class="container">
        <div class="row">

            <% @actors.each do |actor| %>
              <div class="actor col-xs-2">
                <%= image_tag actor.image %>
                <h3> <%= actor.first_name + " " actor.last_name %> </h3>
                <p> <%= actor.bio %> </p>
              </div>
   <%= link_to "Learn more", actor_path(actor) %>
   
            <% end %>

      </div>
</div>

MovieApp/app/views/actors/show.html.erb
<div class="main actor-show">
  <div class="container">
    
    <!-- Display an actor's info here -->
   <div class="actor">
  <%= image_tag @actor.image %>
  <div class="info">
    <h3 class="actor-name"><%= @actor.first_name + " " + @actor.last_name  %></h3>
    <p class="actor-bio"><%= @actor.bio %></p>
  </div>
</div>

    <h2>Movies</h2>
   <% @movies.each do |movie| %>
  <div class="movie">
    <%= image_tag movie.image %>
    <h3 class="movie-title"><%= movie.title %></h3>
    <p class="movie-release-year"><%= movie.release_year %></p>
    <p class="movie-plot"><%= movie.plot %></p>
  </div>
<% end %>

  </div>
</div>

MovieApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolt Movie Database</title>
    <link href='http://fonts.googleapis.com/css?family=Oxygen:300,400,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Montserrat:400,700' rel='stylesheet' type='text/css'>  
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="header">
      <div class="container">
        <img src="https://content.codecademy.com/courses/learn-rails/img/logo.svg" height="40">
        <h1>Bolt Movie Database</h1>
      </div>
    </div>

    <%= yield %>

  </body>
</html>