destinations/config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get 'tags', to: 'tags#index'
  get '/destinationsses/:id', to: 'destinationsses#show', as: :destination

  get '/destinationsses/:id/edit', to: 'destinationsses#edit', as: :edit_destination
  patch '/destinationsses/:id', to: 'destinationsses#update'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

destinations/app/models/destinationss.rb
class Destinationss < ApplicationRecord
    belongs_to :tag
end

destinations/app/models/tag.rb
class Tag < ApplicationRecord
self.table_name = "destinationsses"
end

destinations/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def show
        @destination = Destination.find(params[:id])
    end

    def edit
        @destination = Destination.find(params[:id])
    end

    def update
        @destination = Destination.find(params[:id])
        if @destination.update(destination_params)
            redirect_to(action: 'show', id: @destination.id)
        else
            render 'edit'
        end
    end

private
    def destination_params
        params.require(:destination).permit(:name, :description)
    end
end

destinations/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end
  def show 
    @tag = Tag.find(params[:id]) 
    @destinations = @tag.destinationsses 
  end 
end

destinations/app/helpers/destinations_helper.rb
module DestinationsHelper
end

destinations/app/helpers/tags_helper.rb
module TagsHelper
end

destinations/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Destination" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Destination">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

destinations/app/views/tags/index.html.erb
<div class="header">
  <div class="container">
    <img src="https://content.codecademy.com/courses/learn-rails/img/logo-1tm.svg" width="80">
    <h1>images places</h1>
  </div>
</div>

<div class="tags">
  <div class="container">
    <div class="cards row">
    
      <!--
      To do: Loop through tags and display each one with this HTML
      <div class="card col-xs-4">
        tag's image goes here
        <h2> tag's title goes here </h2>
      </div>
      -->
    <% @tags.each do |t| %>
    <div class="card col-xs-4">
        <%= image_tag t.image %>
        <h2><%= t.title %></h2>
        <%= link_to "Learn more", tag_path(t) %> 
    </div>
    <% end %>
    </div>
  </div>
</div>